# Generated by Django 4.0.3 on 2022-03-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_alter_postsmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='first_post',
            field=models.BooleanField(null=True),
        ),
    ]
